logging:
  level: INFO
  appenders:
    - type: console
      timeZone: IST
      includeCallerData: true
      logFormat: "hazelcast %d [%thread] %-5level %c{15}:%line - %msg%n%rEx"

# Configuration for jetty server
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  minThreads: 100
  maxThreads: 100
  connector:
    port: 8081
    type: http

swagger:
  resourcePackage: "com.test.hazelcast.demo.resource"
  
hazelcastConfig: 
    name: "test-hazelcast-instance"
    password: "test-hazelcast-password"
    networkConfigPort: 8000
    mapStoreConfigs:
      testinfo:  {size: 500000, timeToLiveSeconds: 3600,nearCacheMaxSize: 50000,nearCacheMaxIdleSeconds: 300,nearCacheTimeToLiveSeconds: 3600,nearCacheEvictionPolicy: LFU,backupCount: 1}
